### ISSUE TITLE
How is this different to node-red-node-smooth ?

### ISSUE THREAD

**Issue by dceejay** [eisbehr-/node-red-average#1]
as above... how is this different to to the existing node-red-node-smooth ?

**Comment by dkern** [comment]
Hello @dceejay,

the difference is that `node-red-contrib-average` uses the `msg.topic` to identify values and only calculate the average out of this given set, and not continous on the `msg.payload`.

For example, assume this inputs in given order:

```
1. {"topic":"one","payload":3}
2. {"topic":"two","payload":5}
3. {"topic":"three","payload":7}
4. {"topic":"two","payload":3}
5. {"topic":"one","payload":1}
```

The calculation on the last message is:

```
node-red-contrib-average:  (1 + 3 + 7) / 3
node-red-node-smooth:      (3 + 5 + 7 + 3 + 1) / 5
```

The results would be:

```
node-red-contrib-average:  3.6666666666666665
node-red-node-smooth:      3.8
```

So my purpose is to calulate a exact current average of a fixed given set of numbers by now, and not on an continous input over a longer period.

Hope you understand my point. :wink:

**Comment by dkern** [comment]
An additional note:

I really was not aware that `node-red-node-smooth` had a `average` function at first. The documentation should be more clear on this. It looks like a very specific node and the name `smooth` is missleading here too, imo. Just a hint ...

**Comment by dceejay** [comment]
not sure I understand your example - you have three different topics ? Are you averaging per topic ? so three outputs  (1+3)/2 on topic one , (3+5)/2 on topic two and (7)/1 on topic three ?
Or is it only across the last value received on each topic ? so you would get out in order
3
3+5 / 2
3+5+7 / 3
3+3+7 / 3
1+3+7 / 3  ?

That looks fairly specific also :-) - but I agree it is different to the existing behaviour ! Maybe the docs should say it averages inputs from across different msg.topics to be explicit ?

The Smooth node does more than just average, it can do max, min, high and low pass filters - all different ways of smoothing a stream of data. It defaults to creating the mean (average) and states that in the docs... Renaming it to average would then obscure the other uses.

**Comment by dkern** [comment]
It is across all last values of each topic, yes.

I don't think it's _specific_, it more depends on the usecase. As we're talking on IoT, assume a set of sensors (_maybe some temperature sensors in a big place on different locations_) you want to average to a current value. It's not possible with nodes like `smooth`.

Another thing is, that many sensors or bridges don't send these data syncronous. So it's not said, that the sensors send it's data in the same order and on the same time each measurement. This in mind would make a _period-average_ fairly inaccurate.

Yes, I'm with you. I should make it more clearer in the docs. But as I'm not a native english writer, I'm already searching for a easy description of this behavior. ;)

Thanks!

**Comment by dceejay** [comment]
Yes, all good. Maybe just extend the first line of the info
Calculate the average of incoming msg.payload values from across a number of different msg.topic
???

Also as this is now combining topics... maybe have an option in the config to allow setting the outbound msg.topic. (If set in config use it, else leave as it came in... - which would then indicate where the last value came from..)

**Comment by dkern** [comment]
Thanks for your help. Looks not bad.
And good idea, I will implement this option!

**Comment by dkern** [comment]
I've made your suggested changes and released it already as new version. Thanks for your help.
