### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by marksev1** [eisbehr-/node-red-average#2]
What about for values of temperature, for example, could I set it to show me averages for 24h, 12h, 6h, etc.?

**Comment by dkern** [comment]
Hello @marksev1,

well for this task I would suggest to use `node-red-node-smooth`, when you want to have an continous average.

I use my node for temperatures too, but I don't wanted an average over a longer time, I wanted the exact current average from all sensors. So it returns the exact current average of all inputs, not over a period.

I will update the documentation and try to be more clear on this.

```
+----------+
| Sensor 1 |----------\
+----------+           \
                        \
+----------+             \+---------+            +----------+
| Sensor 2 |--------------| Average |------------|  Result  |
+----------+             /+---------+            +----------+
                        /
+----------+           /
| Sensor 3 |----------/
+----------+
```

**Comment by marksev1** [comment]
Ah I understand now. Thanks for the suggestion! Still a good useful node
also, good job!
