### ISSUE TITLE
how to reset/clear the node?

### ISSUE THREAD

**Issue by mattyg-repo** [eisbehr-/node-red-average#3]
how can i reset or clear the node to process a completely new set of data and get an average only from the new data set?

Thanks

**Comment by dkern** [comment]
Hello @mogmedia,

that is a really good question. It's actually not possible, because I never thougt of this problem. I will implement this for you and tell you here, when it's done. Thanks for the hint!

**Comment by dkern** [comment]
From now on you can reset the node with an incoming message, that contains `msg.reset` as property! Just update the node on your system.

**Comment by mattyg-repo** [comment]
that was super fast! Thanks a lot
